# Generated by Django 5.2.5 on 2025-08-12 17:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessoConvocacao",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("concurso_uuid", models.UUIDField(verbose_name="UUID do Concurso")),
                (
                    "concurso_nome",
                    models.CharField(max_length=200, verbose_name="Nome do Concurso"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "tipo_processo",
                    models.CharField(
                        choices=[
                            ("CONVOCACAO", "Convocação"),
                            ("SELECAO", "Seleção"),
                            ("AVALIACAO", "Avaliação"),
                        ],
                        default="CONVOCACAO",
                        max_length=20,
                        verbose_name="Tipo de Processo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_ANDAMENTO", "Em Andamento"),
                            ("FINALIZADO", "Concluído"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="EM_ANDAMENTO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Publicação",
                    ),
                ),
                (
                    "data_convocacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Convocação",
                    ),
                ),
                (
                    "numero_convocados",
                    models.IntegerField(default=1, verbose_name="Número de Convocação"),
                ),
            ],
            options={
                "verbose_name": "Processo de Convocação",
                "verbose_name_plural": "Processos de Convocação",
                "db_table": "processos_convocacao",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="CargoProcesso",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Cargo"),
                ),
                (
                    "cargo_uuid",
                    models.UUIDField(verbose_name="UUID do Cargo"),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos_processo",
                        to="processos.processoconvocacao",
                        verbose_name="Processo de Convocação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo do Processo",
                "verbose_name_plural": "Cargos do Processo",
                "db_table": "processos_cargos",
                "ordering": ["nome"],
                "unique_together": {("processo", "nome")},
            },
        ),
    ]
