# Generated by Django 5.2.5 on 2025-09-30 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_alter_cargoprocesso_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processoconvocacao',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='processoconvocacao',
            name='numero_convocados',
        ),
        migrations.RemoveField(
            model_name='processoconvocacao',
            name='tipo_processo',
        ),
        migrations.AddField(
            model_name='processoconvocacao',
            name='data_corte_vagas',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Corte de Vagas'),
        ),
        migrations.AddField(
            model_name='processoconvocacao',
            name='tipo_escolha',
            field=models.CharField(choices=[('NOVA_AUTORIZACAO', 'Nova Autorização'), ('REPOSICAO', 'Reposição'), ('RECONVOCAO', 'Reconvocação')], default='NOVA_AUTORIZACAO', max_length=20, verbose_name='Tipo de Escolha'),
        ),
    ]
