# Generated by Django 5.2.5 on 2025-11-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0003_remove_processoconvocacao_data_publicacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargoprocesso",
            name="geral",
            field=models.IntegerField(
                default=0,
                help_text="Quantidade de vagas para candidatos gerais",
                verbose_name="Vagas Gerais",
            ),
        ),
        migrations.AddField(
            model_name="cargoprocesso",
            name="nna",
            field=models.IntegerField(
                default=0,
                help_text="Quantidade de vagas para negros, não-afrodescendentes",
                verbose_name="Vagas NNA",
            ),
        ),
        migrations.AddField(
            model_name="cargoprocesso",
            name="pcd",
            field=models.IntegerField(
                default=0,
                help_text="Quantidade de vagas para pessoas com deficiência",
                verbose_name="Vagas PCD",
            ),
        ),
        migrations.AddField(
            model_name="cargoprocesso",
            name="total_candidatos",
            field=models.IntegerField(
                default=0,
                help_text="Total de candidatos classificados para este cargo",
                verbose_name="Total de Candidatos",
            ),
        ),
        migrations.AddField(
            model_name="cargoprocesso",
            name="vagas",
            field=models.IntegerField(
                default=0,
                help_text="Total de vagas disponíveis para este cargo no processo",
                verbose_name="Quantidade de Vagas",
            ),
        ),
    ]
