# Generated by Django 5.2.5 on 2025-11-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0003_remove_processoconvocacao_data_publicacao_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cargoprocesso",
            options={
                "ordering": ["cargo_nome"],
                "verbose_name": "Cargo do Processo",
                "verbose_name_plural": "Cargos do Processo",
            },
        ),
        migrations.RenameField(
            model_name="cargoprocesso",
            old_name="nome",
            new_name="cargo_nome",
        ),
        migrations.AlterUniqueTogether(
            name="cargoprocesso",
            unique_together={("processo", "cargo_nome")},
        ),
        migrations.AddField(
            model_name="cargoprocesso",
            name="candidatos_geral",
            field=models.IntegerField(
                default=0,
                help_text="Quantidade de candidatos habilitados geral",
                verbose_name="Candidatos Gerais",
            ),
        ),
        migrations.AddField(
            model_name="cargoprocesso",
            name="candidatos_nna",
            field=models.IntegerField(
                default=0,
                help_text="Quantidade de candidatos habilitados nna",
                verbose_name="Candidatos NNA",
            ),
        ),
        migrations.AddField(
            model_name="cargoprocesso",
            name="candidatos_pcd",
            field=models.IntegerField(
                default=0,
                help_text="Quantidade de candidatos habilitados pessoas com deficiência",
                verbose_name="Candidatos PCD",
            ),
        ),
        migrations.AddField(
            model_name="cargoprocesso",
            name="total_candidatos",
            field=models.IntegerField(
                default=0,
                help_text="Total de candidatos classificados para este cargo",
                verbose_name="Total de Candidatos",
            ),
        ),
        migrations.AddField(
            model_name="cargoprocesso",
            name="vagas",
            field=models.IntegerField(
                default=0,
                help_text="Total de vagas disponíveis para este cargo no processo",
                verbose_name="Quantidade de Vagas",
            ),
        ),
    ]
