# Generated by Cursor on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0008_cartaconvocacaocandidato"),
    ]

    operations = [
        migrations.AddField(
            model_name="processoconvocacao",
            name="esta_ativo",
            field=models.BooleanField(default=True, verbose_name="Está ativo"),
        ),
    ]

