# Generated by Django 5.2.5 on 2026-05-20 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0011_processoconvocacao_porcentagem_nna_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvioEmail",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("processo_uuid", models.UUIDField(verbose_name="UUID do Processo")),
                (
                    "processo_nome",
                    models.CharField(max_length=200, verbose_name="Nome do Processo"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CONVOCACAO", "Convocação"),
                            ("VAGAS", "Vagas"),
                            ("RESULTADOS", "Resultados"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de envio",
                    ),
                ),
                (
                    "quantidade_candidatos",
                    models.IntegerField(
                        default=0, verbose_name="Quantidade de candidatos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Envio de e-mail",
                "verbose_name_plural": "Envios de e-mail",
                "db_table": "processos_envio_email",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="EnvioEmailCandidato",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                ("rf", models.CharField(blank=True, max_length=20, verbose_name="RF")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("SUCESSO", "Sucesso"),
                            ("ERRO", "Erro"),
                        ],
                        max_length=20,
                        verbose_name="Status do envio",
                    ),
                ),
                (
                    "status_detalhe",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem de erro ou detalhe do envio",
                        verbose_name="Detalhe do status",
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(
                        blank=True, verbose_name="Conteúdo do email enviado"
                    ),
                ),
                (
                    "envio_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatos",
                        to="processos.envioemail",
                        verbose_name="Envio de e-mail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envio de e-mail - Candidato",
                "verbose_name_plural": "Envio de e-mail - Candidatos",
                "db_table": "processos_envio_email_candidato",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.DeleteModel(
            name="CartaConvocacaoCandidato",
        ),
        migrations.DeleteModel(
            name="CartaConvocacaoHistorico",
        ),
    ]
