# Generated by Django 5.2.5 on 2025-09-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargoprocesso",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="cargoprocesso",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="processoconvocacao",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="processoconvocacao",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
    ]
