# Generated by Django 5.2.5 on 2025-11-13 16:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0004_alter_cargoprocesso_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargoprocesso",
            name="candidatos_uuids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="UUIDs de Candidatos",
            ),
        ),
    ]
