# Generated by Django 5.2.5 on 2025-11-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0005_cargoprocesso_candidatos_uuids"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargoprocesso",
            name="cargo_codigo",
            field=models.CharField(
                default="", max_length=20, verbose_name="Código do Cargo"
            ),
        ),
    ]
