# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0006_cargoprocesso_cargo_codigo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartaConvocacaoHistorico",
            fields=[
                ("uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                ("processo_uuid", models.UUIDField(verbose_name="UUID do Processo")),
                ("processo_nome", models.CharField(max_length=200, verbose_name="Nome do Processo")),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "quantidade_candidatos",
                    models.IntegerField(default=0, verbose_name="Quantidade de Candidatos"),
                ),
            ],
            options={
                "verbose_name": "Histórico de Carta de Convocação",
                "verbose_name_plural": "Históricos de Carta de Convocação",
                "db_table": "processos_carta_convocacao_historico",
                "ordering": ["-criado_em"],
            },
        ),
    ]
