# Generated by Django 5.2.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0007_cartaconvocacaohistorico"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartaConvocacaoCandidato",
            fields=[
                ("uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                ("rf", models.CharField(blank=True, max_length=20, verbose_name="RF")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCESSO", "Sucesso"), ("ERRO", "Erro")],
                        max_length=20,
                        verbose_name="Status do envio",
                    ),
                ),
                (
                    "status_detalhe",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem de erro ou detalhe do envio",
                        verbose_name="Detalhe do status",
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(blank=True, verbose_name="Conteúdo do email enviado"),
                ),
                (
                    "carta_convocacao_historico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatos",
                        to="processos.cartaconvocacaohistorico",
                        verbose_name="Histórico da Carta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carta Convocação - Candidato",
                "verbose_name_plural": "Carta Convocação - Candidatos",
                "db_table": "processos_carta_convocacao_candidato",
                "ordering": ["-criado_em"],
            },
        ),
    ]
