# Generated by Django 5.2 on 2026-04-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0008_cartaconvocacaocandidato"),
    ]

    operations = [
        migrations.AddField(
            model_name="processoconvocacao",
            name="passo",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                default=1,
                verbose_name="Passo",
            ),
        ),
        migrations.AlterField(
            model_name="processoconvocacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("EM_ANDAMENTO", "Em Andamento"),
                    ("FINALIZADO", "Concluído"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDENTE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
