# Generated by Django 5.2.5 on 2026-04-08 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0009_processoconvocacao_esta_ativo"),
        ("processos", "0009_processoconvocacao_passo_and_more"),
    ]

    operations = []
