# Generated by Django 5.2.5 on 2026-05-06 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0010_merge_20260408_1524"),
    ]

    operations = [
        migrations.AddField(
            model_name="processoconvocacao",
            name="porcentagem_nna",
            field=models.FloatField(default=0.2, verbose_name="Porcentagem de NNA"),
        ),
        migrations.AddField(
            model_name="processoconvocacao",
            name="porcentagem_pcd",
            field=models.FloatField(default=0.05, verbose_name="Porcentagem de PCD"),
        ),
        migrations.AlterField(
            model_name="cartaconvocacaocandidato",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("SUCESSO", "Sucesso"),
                    ("ERRO", "Erro"),
                ],
                max_length=20,
                verbose_name="Status do envio",
            ),
        ),
        migrations.AlterField(
            model_name="cartaconvocacaocandidato",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="cartaconvocacaohistorico",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
