# Generated by Django 5.2.5 on 2026-06-11 17:16

from pathlib import Path
import uuid

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


CORPO_POR_TIPO = {
    'CONVOCACAO': 'email_convocacao_padrao.html',
    'VAGAS': 'email_vagas_padrao.html',
    'RESULTADOS': 'email_resultados_padrao.html',
}


def _ler_corpo_template(nome_arquivo: str) -> str:
    path = Path(settings.BASE_DIR) / 'templates' / 'email' / nome_arquivo
    return path.read_text(encoding='utf-8')


def criar_conteudos_iniciais(apps, schema_editor):
    EnvioEmailConteudo = apps.get_model('processos', 'EnvioEmailConteudo')
    agora = timezone.now()
    for tipo, arquivo in CORPO_POR_TIPO.items():
        EnvioEmailConteudo.objects.create(
            uuid=uuid.uuid4(),
            tipo=tipo,
            conteudo_gabarito=_ler_corpo_template(arquivo),
            criado_em=agora,
            atualizado_em=agora,
        )


def remover_conteudos_iniciais(apps, schema_editor):
    EnvioEmailConteudo = apps.get_model('processos', 'EnvioEmailConteudo')
    EnvioEmailConteudo.objects.filter(
        tipo__in=['CONVOCACAO', 'VAGAS', 'RESULTADOS'],
    ).delete()


def zerar_conteudo(apps, schema_editor):
    EnvioEmailConteudo = apps.get_model('processos', 'EnvioEmailConteudo')
    EnvioEmailConteudo.objects.all().update(conteudo='')


def restaurar_conteudo(apps, schema_editor):
    EnvioEmailConteudo = apps.get_model('processos', 'EnvioEmailConteudo')
    for registro in EnvioEmailConteudo.objects.all():
        if registro.conteudo_gabarito:
            conteudo = registro.conteudo_gabarito
        elif registro.tipo in CORPO_POR_TIPO:
            conteudo = _ler_corpo_template(CORPO_POR_TIPO[registro.tipo])
        else:
            continue
        EnvioEmailConteudo.objects.filter(pk=registro.pk).update(conteudo=conteudo)


def aplicar_conteudos(apps, schema_editor):
    criar_conteudos_iniciais(apps, schema_editor)
    zerar_conteudo(apps, schema_editor)


def reverter_conteudos(apps, schema_editor):
    remover_conteudos_iniciais(apps, schema_editor)
    restaurar_conteudo(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0013_envioemailconteudo"),
    ]

    operations = [
        migrations.AddField(
            model_name="envioemailconteudo",
            name="assunto",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Assunto do e-mail"
            ),
        ),
        migrations.AlterField(
            model_name="envioemailconteudo",
            name="conteudo",
            field=models.TextField(
                help_text="Fragmento HTML do corpo (sem cabeçalho PMSP). Variáveis Django: {{ cargo }}, {{ classificacao }}, {{ data_publicacao }}, etc. O layout base vem de templates/email/envio_email.html.",
                verbose_name="Corpo do e-mail (HTML)",
            ),
        ),
        migrations.AddField(
            model_name="envioemailconteudo",
            name="conteudo_gabarito",
            field=models.TextField(
                default="",
                help_text="Fragmento HTML do corpo (sem cabeçalho PMSP). Variáveis Django: {{ cargo }}, {{ classificacao }}, {{ data_publicacao }}, etc. O layout base vem de templates/email/envio_email.html.",
                verbose_name="Corpo do e-mail (HTML)",
            ),
        ),
        migrations.RunPython(aplicar_conteudos, reverter_conteudos),
    ]
